Document another case of GHC-53786
haskellfoundation/error-message-index pull request #364
Opened 2022-12-12 16:49 UTC by mrgutkun

A case-expression inside a do-block whose branch expression is missing a `do` parses unintuitively, resulting in a confusing GHC-53786. It seems worthwhile to document  this explicitly.

2022-12-12 19:13 UTC, david-christiansen requested changes
Nice catch!

I think that the exact phrasing of the description is a bit difficult to read. I suggested a rephrasing - did I capture the meaning correctly?

Thanks!

2022-12-12 19:13 UTC, david-christiansen commented on message-index/messages/GHC-53786/case-expr-in-do-block/index.md
> +The expression in one branch of the case expression is a do-block that's missing a `do`; the whole case-expression is interpreted as LHS of a bind in the top-level do-block. See also: https://gitlab.
```suggestion
The expression in one branch of the case expression is a `do`-block that's missing a `do`. This triggers a corner case in the grammar of Haskell, and the `case`-expression is interpreted as the pattern part of a bind statement in the top-level `do`-block. 

More details are available at https://gitlab.haskell.org/ghc/ghc/-/issues/984
```

2022-12-12 19:13 UTC, david-christiansen commented on message-index/messages/GHC-53786/case-expr-in-do-block/index.md
> +The expression in one branch of the case expression is a do-block that's missing a `do`; the whole case-expression is interpreted as LHS of a bind in the top-level do-block. See also: https://gitlab.
I think that these changes render it a bit easier to follow - the original version had a fairly long sentence that took me a couple of passes. What do you think?

2022-12-12 20:13 UTC, mrgutkun commented on message-index/messages/GHC-53786/case-expr-in-do-block/index.md
> +The expression in one branch of the case expression is a do-block that's missing a `do`; the whole case-expression is interpreted as LHS of a bind in the top-level do-block. See also: https://gitlab.
This does read better, thanks!

2022-12-13 10:27 UTC, david-christiansen approved these changes

2022-12-13 10:28 UTC, merged

2022-12-13 10:28 UTC, david-christiansen commented
Thanks again!