Add guidance about GHCup's pre-release channel
haskellfoundation/error-message-index pull request #373
Opened 2023-01-14 22:01 UTC by tfausak

I ran into this while trying to install ghc GHC 9.6.1-alpha1 using GHCup. The GHCup-000100 page already contains enough information to piece this together, but I figured it was worth an explicit callout.

2023-01-15 19:01 UTC, david-christiansen requested changes

2023-01-15 19:01 UTC, david-christiansen commented on message-index/messages/GHCup-00010/index.md
> +* The version of the tool you specified was a pre-release, like an alpha or release candidate. Add [a release channel](https://www.haskell.org/ghcup/guide/#pre-release-channels) to make it available.
Where does `https://raw.githubusercontent.com/haskell/ghcup-metadata/master/ghcup-prereleases-0.0.7.yaml` come from? The reason I ask is that people who are skimming for solutions might miss the "for example" and then get stuck. A link to a page that discusses how to select this file would be really useful here.

2023-01-15 19:01 UTC, david-christiansen commented
Thanks!

2023-01-16 00:13 UTC, tfausak commented on message-index/messages/GHCup-00010/index.md
> +* The version of the tool you specified was a pre-release, like an alpha or release candidate. Add [a release channel](https://www.haskell.org/ghcup/guide/#pre-release-channels) to make it available.
It comes from the documentation page linked in the previous sentence: https://www.haskell.org/ghcup/guide/#pre-release-channels

2023-01-16 08:46 UTC, david-christiansen commented on message-index/messages/GHCup-00010/index.md
> +* The version of the tool you specified was a pre-release, like an alpha or release candidate. Add [a release channel](https://www.haskell.org/ghcup/guide/#pre-release-channels) to make it available.
What I don't see at the link is where to get prerelease channels from, but I suppose that's more an issue with the linked docs than with this PR. Thanks!

2023-01-16 08:46 UTC, merged

2023-01-16 12:18 UTC, tfausak commented on message-index/messages/GHCup-00010/index.md
> +* The version of the tool you specified was a pre-release, like an alpha or release candidate. Add [a release channel](https://www.haskell.org/ghcup/guide/#pre-release-channels) to make it available.
Oh, I see. As far as I know, there's no list of pre-release channels.