Add GHCup-00160
haskellfoundation/error-message-index pull request #375
Opened 2023-01-16 12:23 UTC by hasufell

2023-01-16 13:02 UTC, david-christiansen requested changes
There are some minor grammatical issues.

Also, it seems to me that the potential causes of the error are distributed throughout the text in a way that requires reading the whole thing to find them. In our current world of short attention spans, what about adding a little summary to the beginning, after "and binary distributions", along the lines of:

> Potential causes include:
>  * No Internet connection
>  * Unreliable disk or Internet leading to a corrupted file
>  * A mistake by the maintainers of GHCup

2023-01-16 13:02 UTC, david-christiansen commented
Thanks!

2023-01-16 13:24 UTC, hasufell commented
> In our current world of short attention spans

I don't know... I could also start a tiktok series on GHCup errors.

On the other hand... maybe a common shared structure for documents would be in order?

2023-01-16 13:49 UTC, david-christiansen commented on message-index/messages/GHCup-00160/index.md
> +summary: GHCup was unable to decode a JSON document (e.g. metadata file)
I think this is enough to remove the stark confusion :-)

2023-01-16 13:50 UTC, david-christiansen commented on message-index/messages/GHCup-00160/index.md
> +title: JSON decoding failed
I don't doubt the truth of what you're saying here. But if I wasn't aware of how Haskell JSON and YAML libraries work, then I might think that the author of the documentation had made a mistake when they wrote "JSON" in an error message description that clearly seems to be about a downloaded YAML file. I added a suggestion to the summary that I think will make people realize it's not a mistake, at least - what do you think?

2023-01-16 13:53 UTC, david-christiansen commented
I haven't yet seen enough commonalities between all the errors to suggest a common format.

In particular, GHC descriptions tend to be very focused around concrete example programs, because most people learn these things best by pattern recognition. Stack and GHCup errors are usually more about bogus command line arguments, strange system configurations, or malfunctioning Internet connections, which suggests a slightly different format.

Perhaps the "before/after" format available to files that contain issues can be extended usefully to shell interaction transcripts?

2023-01-16 13:53 UTC, david-christiansen approved these changes

2023-01-16 14:34 UTC, hasufell commented
let me restructure a bit

2023-01-16 19:19 UTC, david-christiansen commented on message-index/messages/GHCup-00160/index.md
> +The most common cause for this error is when GHCup tries to fetch the metadata file that contains information
(simply because it's not the _fetching_ that causes the error per se, it's that the error is usually due to something that goes wrong with the fetching)

2023-01-16 19:20 UTC, david-christiansen commented on message-index/messages/GHCup-00160/index.md
> +title: JSON decoding failed
We are all subject to that - I'm really trying to review incoming docs from the perspective of a new Haskeller who knows programming in some other language, but it's not always easy to forget what I've learned!

2023-01-16 19:21 UTC, david-christiansen commented
I've got just one extremely pedantic comment, but I'd be OK with it as-is if you feel like you've put in the effort that you have available to you.

2023-01-17 07:59 UTC, merged

2023-01-17 07:59 UTC, david-christiansen commented
Thanks again!