Improve some GHCup errors
haskellfoundation/error-message-index pull request #381
Opened 2023-02-01 08:33 UTC by hasufell

2023-02-13 13:48 UTC, david-christiansen requested changes
First off, sorry for the late answer here.

I suggested a few rephrasings that I think make the text both more specific and less likely to be hurtful. There were also a few capitalization fixes.

2023-02-13 13:48 UTC, david-christiansen commented on message-index/messages/GHCup-00160/index.md
> +* broken curl or wget (e.g. installed through [snap](https://snapcraft.io/))
```suggestion
* Non-functional `curl` or `wget` (users have reported difficulties when these tools are installed through [snap](https://snapcraft.io/))
```

I'd rather be specific than just throw shade

2023-02-13 13:48 UTC, david-christiansen commented on message-index/messages/GHCup-00160/index.md
> +these from your package manager and not via [snap](https://snapcraft.io/) or similar. On windows, make
```suggestion
these from your package manager and not via [snap](https://snapcraft.io/) or similar. On Windows, make
```

What counts as "similar"? How would users know?

2023-02-13 13:48 UTC, david-christiansen commented on message-index/messages/GHCup-00160/index.md
> +If the download succeeds, but the error persists, try examining the file and verify it's valid YAML:
```suggestion
If the download succeeds, but the error persists, try examining the file and verify that it's valid YAML:
```

2023-02-13 13:48 UTC, david-christiansen commented on message-index/messages/GHCup-05841/index.md
>  Reasons for this errors:
```suggestion
Reasons for this error:
```

That wasn't a change in this PR, but I noticed it :-)

2023-02-13 14:10 UTC, hasufell commented on message-index/messages/GHCup-00160/index.md
> +these from your package manager and not via [snap](https://snapcraft.io/) or similar. On windows, make
> What counts as "similar"? How would users know?

Flatpak, AppImage and all the other cr... err, creative solutions.

2023-02-13 14:29 UTC, david-christiansen commented on message-index/messages/GHCup-00160/index.md
> +these from your package manager and not via [snap](https://snapcraft.io/) or similar. On windows, make
Those are common ways to distribute software that are generally recommended by distributions these days. If people have reported difficulties when using them, then we should definitely document those difficulties, but we should expect that people will be using them more and more in the future. I don't think that insulting them is going to make any positive changes here.

So the question remains - are users reporting difficulties using `curl` and/or `wget` from Flatpak or AppImage? If so, we should list them, and if not, then I suggest we just list Snap as something to avoid for now.

2023-02-13 14:31 UTC, david-christiansen requested changes

2023-02-13 14:31 UTC, david-christiansen commented on message-index/messages/GHCup-00160/index.md
> +If the download fails, your curl/wget installation might be broken. On linux, make sure you've installed
```suggestion
If the download fails, your `curl`/`wget` installation might be broken. On Linux, make sure you've installed
```

2023-02-13 14:31 UTC, david-christiansen commented on message-index/messages/GHCup-00160/index.md
> +these from your package manager and not via [snap](https://snapcraft.io/) or similar. On Windows, make
```suggestion
these from your package manager and not via [snap](https://snapcraft.io/), which has been reported to cause problems with `ghcup`. On Windows, make
```

2023-02-13 15:15 UTC, hasufell commented on message-index/messages/GHCup-00160/index.md
> +these from your package manager and not via [snap](https://snapcraft.io/) or similar. On windows, make
> Those are common ways to distribute software that are generally recommended by distributions these days

I don't think that's generally true. The distributions that I've worked with do not seem to recommend those ways (e.g. gentoo, exherbo, archlinux).

And I also generally disagree that those are reasonable architectures.

2023-02-13 15:18 UTC, hasufell commented on message-index/messages/GHCup-00160/index.md
> +these from your package manager and not via [snap](https://snapcraft.io/) or similar. On windows, make
> If so, we should list them, and if not, then I suggest we just list Snap as something to avoid for now.

My recommendation is and will remain to install curl/wget via your package manager and *nothing* else. I will make this more clear.

2023-02-13 15:19 UTC, hasufell commented on message-index/messages/GHCup-00160/index.md
> +these from your package manager and not via [snap](https://snapcraft.io/) or similar. On windows, make
I think I have sufficient autonomy to make that call for GHCup, which makes use of curl and wget.

2023-02-13 19:59 UTC, david-christiansen commented on message-index/messages/GHCup-00160/index.md
> +these from your package manager and not via [snap](https://snapcraft.io/) or similar. On windows, make
I think that:

> My recommendation is and will remain to install curl/wget via your package manager and nothing else.

is a fine way to write it.

My concerns here are that the documentation site is not provoking flame wars or causing others to feel insulted and that any recommendations given are specific and actionable.

2023-02-13 20:00 UTC, david-christiansen commented on message-index/messages/GHCup-00160/index.md
> +these from your package manager and not via [snap](https://snapcraft.io/), [Flatpak](https://flatpak.org/) or [AppImage](https://appimage.org/). GHCup does neither recommend nor support those tools.
```suggestion
these from your package manager and not via [snap](https://snapcraft.io/), [Flatpak](https://flatpak.org/) or [AppImage](https://appimage.org/). GHCup neither recommends nor supports those tools.
```

2023-02-14 06:05 UTC, hasufell commented on message-index/messages/GHCup-00160/index.md
> +these from your package manager and not via [snap](https://snapcraft.io/) or similar. On windows, make
> My concerns here are that the documentation site is not provoking flame wars or causing others to feel insulted and that any recommendations given are specific and actionable.

I totally agree and I'm a bit confused you feel the need to mention this.

I was simply signalling to you that I have a **very low opinion** on the mentioned technologies, because we're discussing this informally here, aren't we?

The documentation should indeed just explain what we're willing to support and what we're considering problematic without making blanket statements.

I think that the current wording achieves that.

2023-02-14 09:29 UTC, david-christiansen commented on message-index/messages/GHCup-00160/index.md
> +these from your package manager and not via [snap](https://snapcraft.io/) or similar. On windows, make
I think that we've been caught out here by the lack of bandwidth of text communication here.

I mentioned those principles out of what is probably an overabundance of clarity: I wanted to make it clear that I was working based on those, rather than on a preference for or against some particular software distribution method. I like being explicit about background assumptions where possible, but explicitly communicating obvious-seeming principles certainly runs the risk of implying that someone else is behaving badly.

I'll commit the grammar fix and merge if it's OK with you. Thanks!

2023-02-14 16:51 UTC, hasufell commented on message-index/messages/GHCup-00160/index.md
> +these from your package manager and not via [snap](https://snapcraft.io/) or similar. On windows, make
Sure

2023-02-21 12:58 UTC, merged

2023-02-21 13:12 UTC, hasufell commented
Thanks