adds OS controlled dark mode
haskellfoundation/error-message-index pull request #383
Opened 2023-02-22 00:22 UTC by jzwood

## Changes
- removes all theme-dependent colors from default css
- adds _theme.css_ with a dark and light color palette that respects the OS theme settings

## How to Test
- run site locally in Chrome
    - stack run -- site watch
- go to settings > appearance (on mac)
    - toggle between Light and Dark mode and see that the page changes color modes

### Screen Shot
<img width="1774" alt="Screenshot 2023-02-21 at 7 15 37 PM" src="https://user-images.githubusercontent.com/13749324/220488059-bf87b482-7802-42ed-a8db-b88bd32b717f.png">

2023-02-22 20:56 UTC, david-christiansen commented
I'll give it a proper test soon!

As far as screenshot-based feedback goes, I have a couple questions:
 * The contrast between the light text and dark background is very high, but the same is not true for things like module names in the code sample (it also looks like the code sample's syntax highlighting is thoroughly off in both sides, but I suspect that this is unrelated to the PR). Looking at e.g. GitHub's dark theme, the contrast between the very dark background and ordinary text seems to be a bit less. How should we think about selecting the right contrast and thus text color?
 * Headers like "Examples" and "Error messages" are very low-contrast, making me think that they are not important. 
 * The pink links seem to jump out quite a bit compared to the other theme
 * Is there a distinction between visited and unvisited links? The current light theme has one, and it would be interesting to know the reasoning.

I'm not at all an expert in design, please answer my questions in ELI5 mode if possible :-) I'll also test it with the GNOME dark mode setting and Firefox - I don't have a Mac handy to test with, but that's what you're using, so this gets us a bit more coverage at least.

Thank you!

2023-02-23 00:07 UTC, jzwood commented
Hi @david-christiansen, thanks for preliminary feedback. You brought up some great points.

I agree that the dark mode headers are too dark and the text is too bright. I made the headers brighter (by eye) and the text a bit darker (to match Github) so that feels a little better. In terms of finding a balance, it's a tad tricky b/c accessibility guidelines recommend high contrast over low but dark users tend to abhor high-contrast UI 😅.

I quite like the pink links but I'm not married to any of these colors so we can tweak as needed. That shade of pink was lifted from how [hackage](https://hackage.haskell.org/) styles links.

Re visited vs unvisited links -- my understanding is that the different [link states](https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Styling_links#link_states) exist for 2 interconnected reasons.
- These distinct states are how links have worked since the beginning of the web so maintaining that behavior will make using the site more intuitive/familiar
- There are accessibility reasons for having link states be visually distinct although I admit it's unclear to me how that's applicable for specifically visited links.

_Final thoughts_: note that I've adding instructions for testing the theme with Firefox and I wanted to clarify that I have not tampered with the light theme at all. It looks like the syntax highlighting is coming from highlight.js so picking out a different theme would be a separate work issue if you wanted something prettier? 😃

2023-02-23 10:48 UTC, david-christiansen commented
Ah, I just saw that Hackage has dark mode - perhaps the best thing to do is to just take their design and colors and run with it.

2023-02-27 13:26 UTC, david-christiansen requested changes
Thanks for your patience!

I'm far from an expert in CSS, so please take any suggestions with a grain of salt. Generally speaking, I really like the use of variables to structure things and make it easier to maintain over time. Variables have only been supported since 2017 in Edge, but Firefox has supported them since 2014 and most other browsers since 2016. I suppose six years is long enough to wait, Haskellers are demographically likely to have updated browsers, and the HTML is semantic enough that the whole thing should be reasonably readable with defaults.

Generally speaking, the whole CSS code became easier to read with these changes.

I left some detailed comments in the code. Thanks again!

2023-02-27 13:26 UTC, david-christiansen commented on message-index/css/theme.css
> +  }
This is a nice hack, but I think it would make more sense to update `highlight.css` to include a dark theme as well, with colors chosen to match the site. I'd be willing to merge this PR without that, though, and open an issue for the future.

2023-02-27 13:26 UTC, david-christiansen commented on message-index/css/theme.css
> +  --code-color: #FAFAFA;
This variable governs the _background_ color of code, but the name (by analogy to `--text-color` above) suggests that it governs the _foreground_ color. What about renaming it to `--code-bg-color`?

2023-02-27 13:26 UTC, david-christiansen commented on message-index/css/theme.css
> +    color: #8B78C5;
For Hackage match:
```suggestion
    color: #D5C5FF;
```

2023-02-27 14:06 UTC, jzwood commented on message-index/css/default.css
> +  overflow-x: auto;
Absolutely! Using `auto` should result the scrollbar being hidden when all of the content fits into view and the scrollbar visible if there's any overflow content. When you have `overflow-x: scroll`, the scrollbar gutter shows up all the time which is undesirable b/c there's no non-hack way to style the scrollbar and on dark mode the scrollbar becomes a garish white rectangle across the screen.

![Screenshot 2023-02-27 at 9 04 33 AM](https://user-images.githubusercontent.com/13749324/221584323-bf277a87-7eff-40b6-aba1-8ae3ea88f388.png)

when we use `auto` we instead get

![Screenshot 2023-02-27 at 8 51 32 AM](https://user-images.githubusercontent.com/13749324/221584473-db1642ab-5293-46d3-9626-14cd32d000fa.png)


![Screenshot 2023-02-27 at 8 53 12 AM](https://user-images.githubusercontent.com/13749324/221584468-476cdff5-181d-42b1-ad40-a4aff02dc37c.png)

2023-02-27 14:35 UTC, david-christiansen commented on message-index/css/default.css
> +  overflow-x: auto;
This will presumably depend on the browser and OS, but I think that your browser/OS combo is common enough that we should do this. Thanks for clearing it up!

2023-02-27 14:36 UTC, jzwood commented on message-index/css/theme.css
> +body {
Good point! This is largely a matter of taste – there's nothing stopping us from scoping on `:root` instead of `body`. I still like scoping on `body` b/c I prefer variables defined in `:root` to be immutable. I know scoping on `body` is effectively global but personally it feels a little dirty to overwrite global scope. That said, if you want me to change it I will. 🙂

2023-02-27 14:49 UTC, jzwood commented on message-index/css/default.css
> +  overflow-x: auto;
My pleasure! I have to get back to work, heh, but I'll respond to the rest of your excellent comment/questions tonight!

2023-02-27 17:53 UTC, david-christiansen commented on message-index/css/theme.css
> +body {
I read a few tutorials on the subject, and they all recommend `:root` for the variables.

This project is a bit funny, in that its a web project being mostly maintained by people who are not experts in the web. Thus, a certain simplicity is important, and I think that adhering to what the docs "out there" say is a good way to make things easier for CSS n00bs (or unreformed CSS-paleolithics like myself) to maintain.

This isn't mutable, is it? My understanding is that this is just a result of CSS specificity rules and media queries, rather than mutation _per se_.

2023-02-27 17:54 UTC, david-christiansen commented on message-index/css/default.css
> +  overflow-x: auto;
I really appreciate it :-) And no stress - dark mode is nice to have, but certainly not a make-or-break feature for the site. Better to keep you relaxed and having fun as a contributor!

2023-02-28 01:54 UTC, jzwood commented on message-index/css/theme.css
> +body {
Fair enough! I'll make it scoped to `:root`

2023-02-28 01:55 UTC, jzwood commented on message-index/css/theme.css
> +  --bg-nav: transparent;
Good catch! 🦅

2023-02-28 01:56 UTC, jzwood commented on message-index/css/theme.css
> +  -moz-osx-font-smoothing: grayscale;
Let me try and remember the motivation for the above 3 times...

2023-02-28 02:08 UTC, jzwood commented on message-index/css/theme.css
> +  -moz-osx-font-smoothing: grayscale;
ok, so those 3 lines were an attempt to make the error message more legible but that's silly -- I should just make it more legible. IMHO it's too small so in my next commit I'm going to bump it up like below.

<img width="491" alt="Screenshot 2023-02-27 at 9 06 37 PM" src="https://user-images.githubusercontent.com/13749324/221734395-6a667cab-0e4e-4df3-beb9-bd5c414da998.png">

2023-02-28 02:15 UTC, jzwood commented on message-index/css/theme.css
> +  text-rendering: optimizeLegibility;
see comments below.

2023-02-28 02:29 UTC, jzwood commented on message-index/css/theme.css
> +    --header-color: #8946C8;
We can brighten the body text for sure but I suspect that the darkened header would not pass an accessibility audit. The contrast between the header text and the background is too close:

<img width="1169" alt="Screenshot 2023-02-27 at 9 27 08 PM" src="https://user-images.githubusercontent.com/13749324/221737588-78c35cfa-befb-4540-acf6-af087a2c7c9a.png">

2023-02-28 02:36 UTC, jzwood commented on message-index/css/theme.css
> +  }
The light theme uses the browser defaults for anchor tags and since I was only altering the dark mode anchor colors I thought it might be less confusing to put it directly inside the dark media query. Since the light theme might be altered I'll variablize these.

2023-02-28 02:47 UTC, jzwood commented on message-index/css/theme.css
> +  }
Agreed and I'm glad you appreciate the stopgap. Pulling in a real dark themed hljs will be a good next step. 👍

2023-02-28 02:48 UTC, jzwood commented on message-index/css/theme.css
> +  --code-color: #FAFAFA;
wise 😑

2023-02-28 03:17 UTC, jzwood commented
Thanks for the thoughtful questions, comments, and suggestions! I think I captured the relevant feedback. Commit 1 addresses those callouts and the next one updates the header and anchor colors to match Hackage's light theme, re your suggestion. 😃 

<img width="1577" alt="Screenshot 2023-02-27 at 10 11 50 PM" src="https://user-images.githubusercontent.com/13749324/221744217-928d0b81-2327-48c3-8a6e-abefab437c96.png">
<img width="1617" alt="Screenshot 2023-02-27 at 10 12 33 PM" src="https://user-images.githubusercontent.com/13749324/221744222-82d1f40d-d043-4142-b182-53d8cbab745d.png">

2023-02-28 03:20 UTC, jzwood commented on message-index/css/default.css
> +  font-size: medium;
`small` is just a little too small.

2023-02-28 09:09 UTC, david-christiansen commented on message-index/css/theme.css
> +    --header-color: #8946C8;
The suggestion here was that we just do what Hackage does. It is clearly possible that I pasted the value incorrectly out of my browser dev tools :-)

2023-02-28 09:10 UTC, david-christiansen commented on message-index/css/theme.css
> +  }
Ah, I think it would be better if we explicitly choose colors for the light theme. I hadn't realized it didn't have values there :-) This is what we get for starting the project CSS-less and then incrementally muddling through.

2023-02-28 09:11 UTC, david-christiansen commented on message-index/css/theme.css
> +  }
And it looks to me like hljs just uses ordinary CSS for styling, which is great. It'll make it really easy to customize based on your skeleton here.

2023-02-28 09:11 UTC, david-christiansen commented on message-index/css/theme.css
> +  --code-color: #FAFAFA;
I'm responsible for maintaining this thing, after all :-)

2023-02-28 09:15 UTC, david-christiansen commented on message-index/css/default.css
> +  font-size: medium;
Looks good!

2023-02-28 09:17 UTC, david-christiansen commented on message-index/css/theme.css
> +    --header-color: #8946C8;
And you did :-)

2023-02-28 09:20 UTC, david-christiansen commented on message-index/css/theme.css
> +  }
OK, #385 is opened to track this.

2023-02-28 09:21 UTC, david-christiansen commented
Will merge as soon as CI is green. Thank you very much!

2023-02-28 09:32 UTC, david-christiansen approved these changes

2023-02-28 09:33 UTC, merged

2023-02-28 14:26 UTC, jzwood commented on message-index/css/theme.css
> +    --header-color: #8946C8;
The Hackage site faked me out too -- the header color _is_ the dark version you see on the right and they use a filter to brighten it to what you see on the left (as you noted), which is pretty confusing. It was easier to just snipe the absolute color value after it was adjusted.

2023-02-28 14:33 UTC, jzwood commented
🥳