Document GHC-01239 (closes #288)
haskellfoundation/error-message-index pull request #391
Opened 2023-03-07 14:32 UTC by jhrcek

Let me try my hand on documenting one of these error messages.

2023-03-07 14:34 UTC, jhrcek commented on message-index/messages/GHC-01239/index.md
> +introduced: TODO
I have no idea how to find out in which version of GHC this error was introduced. Any suggestions?

2023-03-07 19:04 UTC, david-christiansen commented on message-index/messages/GHC-01239/index.md
> +introduced: TODO
All error codes are introduced in 9.6.1, so thus far, it's not so difficult :-)

We should make it more clear that this documents which release the _code_ was introduced in.

2023-03-07 19:11 UTC, david-christiansen requested changes
I think there's a correctness issue in the example.

I also added a few comments about the text style.

2023-03-07 19:11 UTC, david-christiansen commented on message-index/messages/GHC-01239/example1/after/IfInFunAppExpr.hs
> +example = length if True then [1] else
```suggestion
example = length if True then [1] else []
```
Isn't this missing?

2023-03-07 19:11 UTC, david-christiansen commented on message-index/messages/GHC-01239/example1/index.md
> +To pass If-Then-Else expressions as function argument we either have to surround it in parentheses,
```suggestion
To pass If-Then-Else expressions as function arguments, they must either be surrounded in parentheses,
```

2023-03-07 19:11 UTC, david-christiansen commented on message-index/messages/GHC-01239/example1/index.md
> +use function application operator `($)` or enable [`BlockArguments`](https://ghc.gitlab.haskell.org/ghc/doc/users_guide/exts/block_arguments.html#extension-BlockArguments) extension.
```suggestion
used after the function application operator `($)`, or be used where the [`BlockArguments`](https://ghc.gitlab.haskell.org/ghc/doc/users_guide/exts/block_arguments.html#extension-BlockArguments) extension is enabled.
```

2023-03-07 19:11 UTC, david-christiansen commented on message-index/messages/GHC-01239/example1/index.md
> +To pass If-Then-Else expressions as function argument we either have to surround it in parentheses,
Or if my suggested rewrite doesn't fit your taste, at least:
```suggestion
To pass If-Then-Else expressions as function arguments, we either have to surround them in parentheses,
```

2023-03-07 19:11 UTC, david-christiansen commented on message-index/messages/GHC-01239/index.md
> +If you do that you can run into the following error.
Using both "we" and "you" to refer to the reader is potentially confusing. What about:

```suggestion
Because If-Then-Else expressions return values, it makes sense to pass them as input to a function.
However, without language extensions, Haskell's grammar requires parentheses around them in function argument positions.
```

2023-03-07 19:11 UTC, david-christiansen commented
And thank you!

2023-03-08 05:15 UTC, jhrcek commented on message-index/messages/GHC-01239/example1/after/IfInFunAppExpr.hs
> +example = length if True then [1] else
How did that creep in? :smile:

2023-03-08 05:15 UTC, jhrcek commented on message-index/messages/GHC-01239/example1/index.md
> +To pass If-Then-Else expressions as function argument we either have to surround it in parentheses,
Went with the first one as I find it more natural.

2023-03-08 05:16 UTC, jhrcek commented
Thanks for suggestions! Applied.

2023-03-08 11:04 UTC, david-christiansen commented on message-index/messages/GHC-01239/example1/index.md
> +use function application operator `($)` or enable [`BlockArguments`](https://ghc.gitlab.haskell.org/ghc/doc/users_guide/exts/block_arguments.html#extension-BlockArguments) extension.
I think the grammar is still a bit off. Here's a minimal fix:
```suggestion
use the function application operator `($)` or enable the [`BlockArguments`](https://ghc.gitlab.haskell.org/ghc/doc/users_guide/exts/block_arguments.html#extension-BlockArguments) extension.
```

2023-03-08 11:09 UTC, jhrcek commented on message-index/messages/GHC-01239/example1/index.md
> +use function application operator `($)` or enable [`BlockArguments`](https://ghc.gitlab.haskell.org/ghc/doc/users_guide/exts/block_arguments.html#extension-BlockArguments) extension.
Thanks for pointing that out. I'm not native speaker and I always had a bit of an issue with articles :blush:

2023-03-16 09:02 UTC, david-christiansen approved these changes

2023-03-16 09:03 UTC, david-christiansen commented
Sorry for the slow turnaround here! And thank you for the contribution.

2023-03-16 09:03 UTC, merged