Document GHC-46537 Unsupported extension
haskellfoundation/error-message-index pull request #399
Opened 2023-04-16 09:05 UTC by jhrcek

2023-04-16 20:01 UTC, david-christiansen requested changes
I found a few nitpicky details.

Thanks!

2023-04-16 20:01 UTC, david-christiansen commented on message-index/messages/GHC-46537/index.md
> +2. You're using older version of GHC which doesn't yet support given extension.
```suggestion
2. You're using older version of GHC that doesn't yet support the extension.
```
It should be "that" because "doesn't yet support ..." is a restrictive clause (that is, the sentence makes no sense without it - it's not just some extra info bolted on)

2023-04-16 20:01 UTC, david-christiansen commented on message-index/messages/GHC-46537/index.md
> +    Here's a couple of things you can try to troubleshoot:
```suggestion
    Here's a couple of things you can try in order to troubleshoot:
```

2023-04-16 20:01 UTC, david-christiansen commented on message-index/messages/GHC-46537/index.md
> +    - Find out what version of GHC you're using:
```suggestion
    - Find out which version of GHC you're using:
```

2023-04-16 20:01 UTC, david-christiansen commented on message-index/messages/GHC-46537/index.md
> +    - List all the supported extension that this version of GHC supports. Does the list contain your desired extension?
```suggestion
    - List all the supported extensions that this version of GHC supports. Does the list contain your desired extension?
```

2023-04-16 20:01 UTC, david-christiansen commented on message-index/messages/GHC-46537/index.md
> +    - Search for the extension name in the latest version of [GHC User's Guide](https://downloads.haskell.org/ghc/latest/docs/users_guide/exts.html). Most extensions have a `since` annotation which t
```suggestion
    - Search for the extension name in the latest version of the [GHC User's Guide](https://downloads.haskell.org/ghc/latest/docs/users_guide/exts.html). Most extensions have a `since` annotation which tells you in which version of GHC the extension was introduced.
```

2023-04-17 03:59 UTC, jhrcek commented
Thanks for review, suggestions applied.

2023-04-17 13:13 UTC, david-christiansen approved these changes

2023-04-17 13:13 UTC, merged

2023-04-17 13:13 UTC, david-christiansen commented
Thank you!