Document DsOverflowedLiterals -> 97441 (closes #2)
haskellfoundation/error-message-index pull request #404
Opened 2023-04-17 16:24 UTC by jhrcek

I'm not very happy about the way I present this, suggestions welcome :smile:

2023-04-17 18:29 UTC, david-christiansen requested changes
Thanks! A few suggestions :-)

2023-04-17 18:29 UTC, david-christiansen commented on message-index/messages/GHC-97441/example1/index.md
> +title: Overflowed Literal
```suggestion
title: Overflowed Literals
```

2023-04-17 18:29 UTC, david-christiansen commented on message-index/messages/GHC-97441/example1/index.md
> +    Literal 9223372036854775817 is out of the Int range -9223372036854775808..9223372036854775807
Is this range system-specific? If so, we should probably write that somewhere here (and say what OS and processor you're on)

2023-04-17 18:29 UTC, david-christiansen commented on message-index/messages/GHC-97441/index.md
> +Warning emitted if a literal (constant value in the source code) will overflow.
```suggestion
This warning is emitted if an integer literal (that is, a constant integer value in the source code) will overflow.
```
I'd also add something like the following sentences:
> Many integer types have fixed precision. This means that only a certain number of bits are available to represent their values, which means that there are maximum and minimum values. Calculations that exceed this range cause the value to wrap around, which is called "overflow" or "underflow". Literals outside the range also overflow.

2023-04-17 18:29 UTC, david-christiansen commented on message-index/messages/GHC-97441/index.md
> +- Use different value for the literal so that it fits within the range supported by its type
```suggestion
- Use a different value for the literal so that it fits within the range supported by its type
```

2023-04-17 18:29 UTC, david-christiansen commented on message-index/messages/GHC-97441/index.md
> +- Use different type, which is capable of representing the value
```suggestion
- Use a type that is capable of representing the value (or `Integer`, which can represent values as big as your computer's memory)
```

2023-04-18 14:32 UTC, jhrcek commented on message-index/messages/GHC-97441/example1/index.md
> +    Literal 9223372036854775817 is out of the Int range -9223372036854775808..9223372036854775807
I think it is. Added a sentence along those lines to the main page of this error.

2023-04-18 14:33 UTC, jhrcek commented on message-index/messages/GHC-97441/example1/index.md
> +title: Overflowed Literal
Applied.

2023-04-18 14:33 UTC, jhrcek commented
Sorry for force push, for some reason github wasn't showing the 2nd commit so I rebased on main and force pushed.

2023-04-19 07:20 UTC, david-christiansen requested changes
Thanks! Once again, a couple nitpicky bits :-)

I think that the new content is very useful, it's a big improvement over my last round of suggestions.

2023-04-19 07:20 UTC, david-christiansen commented on message-index/messages/GHC-97441/index.md
> +You can check the minimum / maximum values representable by given type by using `minBound` / `maxBound` from [Bounded](https://hackage.haskell.org/package/base-4.18.0.0/docs/Prelude.html#t:Bounded) t
```suggestion
You can check the minimum and maximum values representable by given type by using `minBound` and `maxBound` from the [Bounded](https://hackage.haskell.org/package/base-4.18.0.0/docs/Prelude.html#t:Bounded) type class defined in the `base` package. The range of supported values might differ based on what OS / platform you’re using.
```

2023-04-19 07:20 UTC, david-christiansen commented on message-index/messages/GHC-97441/index.md
> +You can check the minimum / maximum values representable by given type by using `minBound` / `maxBound` from [Bounded](https://hackage.haskell.org/package/base-4.18.0.0/docs/Prelude.html#t:Bounded) t
There are differences of opinion on the spelling of "type class" or "typeclass". I usually try to follow the original Wadler and Blott paper and write "type class".

2023-04-19 07:20 UTC, david-christiansen commented on message-index/messages/GHC-97441/index.md
> +Calculations that exceed this range cause the value to wrap around, which is called "overflow" or "underflow". Literals outside the range also overflow. This doesn't cause error at runtime, but might
```suggestion
Calculations that exceed this range cause the value to wrap around, which is called "overflow" or "underflow". Literals outside the range also overflow. This doesn't cause an error at runtime, but it might cause confusion because the overflowed value is usually not what you want or expect.
```

2023-04-19 07:34 UTC, david-christiansen approved these changes

2023-04-19 07:35 UTC, david-christiansen commented
That was fast! Thanks again!

2023-04-19 07:35 UTC, merged