(WIP) Small tool for generating the scaffolding of a new error message.
haskellfoundation/error-message-index pull request #408
Opened 2023-04-19 14:24 UTC by BinderDavid

Small tool for creating new error messages more easily.
```console
$> runghc helper-tool.hs 
This tool helps you create the scaffolding for a new error message on the error-message-index.
You can leave any of the text fields blank and fill them in by hand later.

For which system do you want to generate a message?
 1) GHC
 2) GHCup
 3) Stack
Input (Default = GHC): 1

What is the errorcode that you want to document.
Input: 123456

What is the title of the error message.
Input: Missing Binding

Give a short summary of the error message.
Input: A type signature was given, but the binding is missing

What is the severity of the diagnostic.
 1) Error
 2) Warning
 3) N/A
Input (Default = N/A): 1

For which version was this error message emitted for the first time?
Note: For GHC this is most likely 9.6.1.
Input: 9.6.1

How many examples should be generated?
Input: 2
Creating scaffolding for the following configuration:
MkTemplate {system = GHC, code = "123456", title = "Missing Binding", summary = "A type signature was given, but the binding is missing", severity = Error, warningflag = Nothing, introduced = "9.6.1", examples = 2}

```

2023-04-19 17:35 UTC, david-christiansen commented on message-index/helper-tool.hs
> +    case ln of
I'd compare these strings case-insensitively and modulo leading and trailing whitespace for the sake of friendliness

2023-04-19 17:38 UTC, david-christiansen commented on message-index/helper-tool.hs
> +    putStrLn "How many examples should be generated?"
What about interactively prompting for example names instead? Or, alternatively, have a command-line app for adding an example to an existing message?

The concern here is that we  end up with a ton of `example2` directories instead of things with meaningful names. Not that it's the end of the world, though.

2023-04-19 17:39 UTC, david-christiansen commented
This is a good idea! It'll simplify a lot of things. We have a shell script somewhere in the repo that does something similar, but this one seems much easier to use.

2023-04-20 12:35 UTC, BinderDavid commented on message-index/helper-tool.hs
> +    putStrLn "How many examples should be generated?"
I prompt the user for names of the examples now.

2023-05-02 18:22 UTC, david-christiansen requested changes
A few fairly small comments.

I think that this is also much more useful if it includes easy instructions for running it.

2023-05-02 18:22 UTC, david-christiansen commented on message-index/helper-tool.hs
> +  putStrLn "For which system do you want to generate a message?"
I think that we call them "tools" elsewhere in the docs, rather than "tools".

```suggestion
  putStrLn "For which tool do you want to generate a message?"
```
or even
```suggestion
  putStrLn "Which tool's error code do you want to document?"
```

2023-05-02 18:22 UTC, david-christiansen commented on message-index/helper-tool.hs
> +    _ -> pure GHC
Doesn't this mean that typing `stcak` would get me docs for GHC? I'd expect the default to happen for empty input, not necessarily garbage input.

2023-05-02 18:22 UTC, david-christiansen commented on message-index/helper-tool.hs
> +    _ -> pure GHC
```suggestion
    "" -> pure GHC
    _ -> do
      putStrLn "Didn't understand input. Please type a tool name or a number."
      readSystem
```

2023-05-02 18:22 UTC, david-christiansen commented on message-index/helper-tool.hs
> +  putStr "Input: "
This may not work reliably without turning off line buffering on stdout.

2023-05-02 18:22 UTC, david-christiansen commented on message-index/helper-tool.hs
> +  putStrLn "What is the title of the error message."
```suggestion
  putStrLn "What is the title of the error message?"
```

2023-05-02 18:22 UTC, david-christiansen commented on message-index/helper-tool.hs
> +  putStrLn "What is the title of the error message."
Perhaps also include a quick description of what this is used for, e.g. "This is used as the title of the documentation page as well as in links to the page."

2023-05-02 18:22 UTC, david-christiansen commented on message-index/helper-tool.hs
> +  putStrLn "Give a short summary of the error message."
I'd also add "This appears on the overview page that lists all the documented errors and warnings"

2023-05-02 18:22 UTC, david-christiansen commented on message-index/helper-tool.hs
> +    _ -> pure Error
```suggestion
   "" -> pure Error
    _ -> do
      putStrLn "Please type \"error\" or \"warning\" or a number."
      readSeverity
```

2023-05-02 18:22 UTC, david-christiansen commented on message-index/helper-tool.hs
> +  putStrLn "What is the warning flag which enables this warning."
```suggestion
  putStrLn "What is the warning flag which enables this warning?"
```

2023-05-02 18:22 UTC, david-christiansen commented on message-index/helper-tool.hs
> +  Just <$> getLine
This is also something that many users may trip over. What about adding "Please leave this blank if you're not sure."?

2023-05-02 18:22 UTC, david-christiansen commented on message-index/helper-tool.hs
> +    (Just n) -> forM [1 .. n] readExample
```suggestion
    Just n -> forM [1 .. n] readExample
```

2023-05-02 18:22 UTC, david-christiansen commented on message-index/helper-tool.hs
> +            "title: " <> title tmpl,
Do we have to worry about any of the complicated YAML coercion rules here?

2023-05-02 18:22 UTC, david-christiansen commented on message-index/helper-tool.hs
> +  -- - "messages/XXX-NNNNNN/after/" and "messages/XXX-NNNNNN/after/Module.hs"
This comment seems incorrect to me. Shouldn't there be a `messages/XXX-NNNNN/informative-example-name/index.md` and so on?

2023-05-02 18:22 UTC, david-christiansen commented on message-index/helper-tool.hs
> +validateExampleName :: String -> Bool
I think that this should also encourage example names to be lowercase

2023-05-02 18:22 UTC, david-christiansen commented on message-index/helper-tool.hs
> +  -- - "messages/XXX-NNNNNN/after/" and "messages/XXX-NNNNNN/after/Module.hs"
I think the code is right, just not the comment

2023-05-02 18:22 UTC, david-christiansen commented on message-index/helper-tool.hs
> +    writeFile (example_dir </> "before" </> "Example.hs") before_module
What about basing the file name `Example.hs` on the `example` string? Something like uppercasing the first letter and adding `.hs`? This makes it easier for people who download the code and work with it to keep track

2023-05-02 18:23 UTC, david-christiansen commented
Thanks for this, I think it really lowers the barriers to contribution!

2023-05-03 15:06 UTC, BinderDavid commented on message-index/helper-tool.hs
> +  putStrLn "For which system do you want to generate a message?"
Done in [aaa4dec](https://github.com/haskellfoundation/error-message-index/pull/408/commits/aaa4deca07075d4eb49e9acb9434ff564ddfa289)

2023-05-03 15:06 UTC, BinderDavid commented on message-index/helper-tool.hs
> +    _ -> pure GHC
Done in [aaa4dec](https://github.com/haskellfoundation/error-message-index/pull/408/commits/aaa4deca07075d4eb49e9acb9434ff564ddfa289)

2023-05-03 15:06 UTC, BinderDavid commented on message-index/helper-tool.hs
> +  putStrLn "What is the title of the error message."
Done in [aaa4dec](https://github.com/haskellfoundation/error-message-index/pull/408/commits/aaa4deca07075d4eb49e9acb9434ff564ddfa289)

2023-05-03 15:08 UTC, BinderDavid commented on message-index/helper-tool.hs
> +            "title: " <> title tmpl,
I am not sure about what YAML accepts or doesn't accept, and how to test this in the script without writing complex validation logic :man_shrugging: I hope that incorrect YAML will be caught by the CI when trying to build the site.

2023-05-03 15:10 UTC, BinderDavid commented
I applied all of the changes you suggested in the commit [aaa4dec](https://github.com/haskellfoundation/error-message-index/pull/408/commits/aaa4deca07075d4eb49e9acb9434ff564ddfa289) except for the YAML validation, which would probably be quite complex. 

W.r.t documenting the usage of this tool, I hope that we can handle this in #409

2023-05-24 14:19 UTC, david-christiansen commented on message-index/helper-tool.hs
> +            "title: " <> title tmpl,
I think that incorrect YAML is more likely to create icky output HTML than it is to actually cause an error message, unfortunately. But we can always add quotes around things if we need to afterwards.

2023-05-24 14:21 UTC, david-christiansen approved these changes

2023-05-24 14:21 UTC, david-christiansen commented
I would prefer a more descriptive name like @ulysses4ever, but I don't think it's a blocker. Better to get this in here prior to Zurihac!

2023-05-25 14:53 UTC, BinderDavid commented
> I would prefer a more descriptive name like @ulysses4ever, but I don't think it's a blocker. Better to get this in here prior to Zurihac!

Renamed it to `create-message-template.hs` :)

2023-05-25 14:53 UTC, merged

2023-05-25 18:26 UTC, david-christiansen commented
:fireworks: