Add docs for GHC-04584
haskellfoundation/error-message-index pull request #423
Opened 2023-06-10 15:15 UTC by TauOmicronMu

Closes #278

Think this reads alright :)

2023-06-10 15:29 UTC, BinderDavid commented on message-index/messages/GHC-04584/matchingdots/index.md
> +When pattern matching, Expressions are not allowed as patterns to be matched against. Instead, consider matching on a list, and using a conditional.
Expressions > expressions

2023-06-10 15:29 UTC, BinderDavid commented on message-index/messages/GHC-04584/index.md
> +summary: There has been an attempt to pattern match on Expression syntax.
Expression > expression

2023-06-10 15:31 UTC, BinderDavid requested changes
Looks very good :) I think there are just 2 remaining small changes in capitalization.

2023-06-10 15:41 UTC, david-christiansen requested changes
There's a general style thing to make it consistent with the rest of the docs. The example is really well-chosen.

2023-06-10 15:41 UTC, david-christiansen commented on message-index/messages/GHC-04584/index.md
> +## Example Text
Normally we have a general description of the error here, and then specific instances of the error included with the programs that generate them.

I'd use a text like "Pattern matching allows constructors and literals to be used to take apart values, exposing their contents. The syntax of patterns is very similar to that of the expressions that create values, but many constructs that are allowed in expression contexts are not meaningful patterns. "

2023-06-10 16:11 UTC, david-christiansen requested changes

2023-06-10 16:11 UTC, david-christiansen commented on message-index/messages/GHC-09646/index.md
> +Pattern matching allows constructors and literals to be used to take apart values, exposing their contents. The syntax of patterns is very similar to that of the expressions that create values, but m
Here, I'd use a more specific text for this specific variation.

```suggestion
[Tuple sections](https://ghc.gitlab.haskell.org/ghc/doc/users_guide/exts/tuple_sections.html) are a concise syntax for functions that result in tuples. The missing expressions in the tuple become arguments to the function. Because tuple sections always result in functions, and functions cannot be matched in patterns, tuple sections are not allowed in patterns.
```

2023-06-10 16:11 UTC, david-christiansen commented on message-index/messages/GHC-09646/snd/index.md
> +When pattern matching, tuple sections are not allowed as patterns to be matched against. In the example below, we can fix this by adding the wildcard _ to match on the first element of the pair.
I would explain the intent behind the example more. E.g.
```suggestion
When pattern matching, tuple sections are not allowed as patterns to be matched against. In the example below, one of the components of a tuple pattern was forgotten. We can fix this by adding the wildcard _ to match on the first element of the pair.  
```

2023-06-10 16:11 UTC, david-christiansen commented
Looks like we had a review race condition!

2023-06-10 16:18 UTC, TauOmicronMu commented on message-index/messages/GHC-09646/index.md
> +Pattern matching allows constructors and literals to be used to take apart values, exposing their contents. The syntax of patterns is very similar to that of the expressions that create values, but m
Have removed the GHC-09646 stuff from this PR and put it onto a new branch - didn't mean for it to come through here. I'll make the requested changes before sending the new PR over though.

2023-06-10 16:20 UTC, david-christiansen approved these changes

2023-06-10 16:20 UTC, david-christiansen commented on message-index/messages/GHC-09646/index.md
> +Pattern matching allows constructors and literals to be used to take apart values, exposing their contents. The syntax of patterns is very similar to that of the expressions that create values, but m
Thanks!

2023-06-10 16:21 UTC, david-christiansen commented
@BinderDavid I'll let you approve before a merge

2023-06-11 12:05 UTC, BinderDavid approved these changes

2023-06-11 12:06 UTC, merged