Add docs for GHC-07626
haskellfoundation/error-message-index pull request #431
Opened 2023-06-11 13:43 UTC by TauOmicronMu

Closes #266 

Modified example and some text from http://wiki.haskell.org/GHC/Error_messages

2023-06-22 13:00 UTC, david-christiansen requested changes
There's some inconsistent Markdown in the documentation for the example. Otherwise, this is great!

2023-08-09 11:17 UTC, tomjaguarpaw commented
Looks like this is ready for final review?

2023-08-11 11:36 UTC, david-christiansen approved these changes

2023-08-11 11:37 UTC, david-christiansen commented
Yes, thanks for the poke!

2023-08-11 11:37 UTC, merged