Attempt at documenting `83865`
haskellfoundation/error-message-index pull request #436
Opened 2023-06-12 10:24 UTC by VictorCMiraldo

That's a tricky error code, it shows up in many situations (https://gitlab.haskell.org/ghc/ghc/-/issues/23466), but at the same time it is one of the errors that beginners will hit the most. I attempted to document what I believe are the two situations where 83865 will appear first when someone is learning Haskell, so I tried to keep the examples almost trivially simple and the explanations short and concise. What do you folks think?

2023-06-12 10:40 UTC, jhrcek commented on message-index/messages/GHC-83865/index.md
> +summary: You a value of a given type, whereas GHC expected a different type.
Seems like a verb is missing (You <what> a value of a given type)

2023-06-13 14:33 UTC, VictorCMiraldo commented on message-index/messages/GHC-83865/index.md
> +summary: You a value of a given type, whereas GHC expected a different type.
Fixed, thanks! :)

2023-06-13 15:02 UTC, VictorCMiraldo commented
I'm trying to address #438 as part of this PR, since this particular error is a great test case for it, but it seems like Hakyll insists in ignoring the order of the list it is given. I didn't have time to dig into Hakylls source code to check that yet. @david-christiansen, would you have an idea?

2023-06-13 15:06 UTC, david-christiansen commented
I'm stuck in travel mode (flight chaos), so I'm not sure when I can look, but I will do it when I can! We sort lists all the time in the HF website code, so it should be possible.

2023-06-13 15:06 UTC, david-christiansen commented
Thanks for looking into this!

2023-06-13 15:07 UTC, VictorCMiraldo commented
Thanks for the quick reply, I'll try a little longer tomorrow! Safe travels

2023-06-19 08:13 UTC, VictorCMiraldo commented
@david-christiansen turns out I was trying to sort the wrong thing, I got it working this morning! :tada:

2023-06-22 12:15 UTC, david-christiansen requested changes
Thanks for this!

I have some minor nitpicks - what do you think?

2023-06-22 12:15 UTC, david-christiansen commented on message-index/messages/GHC-83865/terms/index.md
> +and ask for it with `:type` (or its shorthand `:t`):
```suggestion
with the command `:type` (or its shorthand `:t`):
```

2023-06-22 12:15 UTC, david-christiansen commented on message-index/messages/GHC-83865/type-kind-mism/index.md
> +Recall that the arrow (`->`) in Haskell is a type constructor, it takes two types
```suggestion
The arrow (`->`) in Haskell is a _type constructor_. It takes two types
```
I'm not a fan of "recall" in this context, because it implies that a reader should already know this information. But I can imagine many situations where exactly this document is someone's first language documentation for Haskell, so we can't expect them to.

2023-06-22 12:15 UTC, david-christiansen commented on message-index/site.hs
> +  deriving (Eq, Ord, Show)
I think that this code would be a bit more clear if the `Ord` instance were not derived. This is because we're not using `Ord` just to stick the value into a binary tree or something - it's being used for the precise semantics of what is bigger than what.
```suggestion
  deriving (Eq, Show)

instance Ord ExampleOrder where
  compare (InGroup i) (InGroup j) = compare i j
  compare (InGroup _) Last = LT
  compare Last (InGroup _) = GT
  compare Last Last = EQ  
```

2023-06-22 12:44 UTC, VictorCMiraldo commented on message-index/messages/GHC-83865/type-kind-mism/index.md
> +Recall that the arrow (`->`) in Haskell is a type constructor, it takes two types
That makes a lot of sense!

2023-06-22 12:45 UTC, VictorCMiraldo commented on message-index/site.hs
> +  deriving (Eq, Ord, Show)
Very fair! Plus if someone ever changes the order of constructors by accident, they don't mess up the orderings on the website.

2023-06-22 12:46 UTC, VictorCMiraldo commented
Thank you for the suggestions and for writing them as clickable suggestions, @david-christiansen! I agree with all and have had them applied!

2023-06-26 13:42 UTC, VictorCMiraldo commented on message-index/site.hs
> +  compare Last Last = EQ
```suggestion
  compare Last Last = EQ
```

2023-07-09 10:24 UTC, BinderDavid approved these changes
The ordering seems to work on my computer, and you adressed all the requested changes w.r.t to the wording. So this now looks good to me 👍

2023-07-09 10:24 UTC, merged