Document error GHC-05380
haskellfoundation/error-message-index pull request #440
Opened 2023-06-15 19:10 UTC by jorisburgers

Fixes https://github.com/haskellfoundation/error-message-index/issues/274

Document the `newtype can only have 1 constructor` error.

2023-06-22 12:02 UTC, david-christiansen requested changes
This looks good! I have a few comments on details of the phrasing. What do you think?

2023-07-16 12:36 UTC, jorisburgers commented
@david-christiansen Sorry for the delayed response. I like your suggestions and have applied them all.

2023-07-16 19:01 UTC, david-christiansen approved these changes

2023-07-16 19:01 UTC, merged

2023-07-16 19:01 UTC, david-christiansen commented
Thanks! Looks great!