Add GHC-25897
haskellfoundation/error-message-index pull request #448
Opened 2023-08-09 11:16 UTC by tomjaguarpaw

2023-08-11 11:34 UTC, david-christiansen requested changes
There's a couple small style changes that would be nice - if you don't have the bandwidth, let me know and I can do them.

2023-08-11 11:34 UTC, david-christiansen commented on message-index/messages/GHC-25897/index.md
> +inferred from its context.
Minor nitpick: I think that this "for example" is a bit confusing - my first read was that it was providing examples of reasons that this knowledge was needed, rather than ways in which it could be found. Here's one rephrasing that I think addresses it:

```suggestion
A pattern match on a GADT cannot succeed unless GHC knows the result
type of the pattern match. This information might, for example, be derived from a type
signature, or by type inference due to the context in which the pattern match occurs.
```

2023-08-11 11:34 UTC, david-christiansen commented on message-index/messages/GHC-25897/index.md
> +```
This message is really associated with `example1` rather than with the overall description - what about moving it to `example1/index.md` along with a brief specific description of the  example, along the lines of "This example uses a GADT pattern match in the definition `foo1`, which has no type signature. Adding a type signature causes the example to be accepted."

2023-08-11 11:34 UTC, david-christiansen commented on message-index/messages/GHC-25897/example1/after/Example1.hs
> +  FB -> False
I worry that adding extra content on the "fixed" side will distract from the fix to the error message on the left. Could this be made into a second broken/fixed example at the cost of being a bit repetitive?

2023-08-11 12:32 UTC, tomjaguarpaw commented
The wording around "for example" is fine by me. Regarding the examples I think it's better if you do them since I think it will take an order of magnitude more time for me to understand your intention than for you to do it. I'm sure I'll be happy with whatever you come up with :)

2023-08-14 20:27 UTC, merged

2023-08-14 20:41 UTC, david-christiansen commented
All right - I went ahead and did it. Thanks for the contribution!