Document GHC-59840
haskellfoundation/error-message-index pull request #450
Opened 2023-08-14 18:07 UTC by BinderDavid

Fixes #112 

This one is for the connaisseurs :)

2023-08-14 20:10 UTC, david-christiansen requested changes
This is a hairy one! Well done!

2023-08-14 20:10 UTC, david-christiansen commented on message-index/messages/GHC-59840/linearPolyType/index.md
> +title: <insert a title for this example here>
This title seems uninformative... What about "Unsupported multiplicity equality in GADT" or something like that?

2023-08-14 20:10 UTC, david-christiansen commented on message-index/messages/GHC-59840/linearPolyType/after/LinearPolyType.hs
> +-- This program can currently not be written :(
```suggestion
-- This program cannot currently be written
```

2023-08-14 20:10 UTC, david-christiansen commented on message-index/messages/GHC-59840/index.md
> +- Linear types, which supports functions like `a %m -> b`. In this function type `m` stands for a *multiplicity* which can be either `One`(also written `1`) or `Many`, depending on how often the argu
```suggestion
- Linear types, which supports functions like `a %m -> b`. In this function type `m` stands for a *multiplicity* which can be either `One`(also written `1`) or `Many`, which determines how often the argument to the function may be used in the body of the function.
```

2023-08-15 02:25 UTC, BinderDavid commented on message-index/messages/GHC-59840/linearPolyType/index.md
> +title: <insert a title for this example here>
Oh 😅 . I updated the title of the example.

2023-08-15 02:26 UTC, merged