Add GHCup-00210
haskellfoundation/error-message-index pull request #458
Opened 2023-08-26 11:36 UTC by hasufell

2023-08-28 13:07 UTC, david-christiansen requested changes
This is very useful - thank you!

I think that a bit more context could help more users understand what's going on here. If these suggestions are OK with you, then I'm happy to apply them myself to save you the effort.

2023-08-28 13:07 UTC, david-christiansen commented on message-index/messages/GHCup-00210/index.md
> +GHCup was asked to verify all downloaded yaml files via GPG. E.g.
```suggestion
GHCup receives information about available Haskell tools through a metadata file in YAML format that describes where to find the tools. As a defense against unauthorized third parties misleading GHCup into installing malicious software, GHCup supports checking that these metadata files are signed by a trusted [GPG](https://en.wikipedia.org/wiki/GNU_Privacy_Guard) key. This error occurs when GHCup was asked to verify all downloaded YAML files via GPG. E.g.
```

I think it's useful to provide a bit more context about where this error comes from, what the files involved are, and which role they're playing. This will also help users evaluate whether they want to turn off the strict checks temporarily or wait for someone else to resolve the situation.

2023-08-28 13:07 UTC, david-christiansen commented on message-index/messages/GHCup-00210/index.md
> +
```suggestion

## Troubleshooting
```

2023-08-28 13:07 UTC, david-christiansen commented on message-index/messages/GHCup-00210/index.md
> +Make sure the remote file exists. It's named the same as the yaml, except it ends with `.sig`. E.g.:
```suggestion
First, make sure the remote file exists. It's name is the same as the YAML file, except it ends with `.sig`. For example:
```

2023-08-28 13:07 UTC, david-christiansen commented on message-index/messages/GHCup-00210/index.md
> +Run ghcup with `-v` to see the exact gpg error, e.g.:
```suggestion
Finally, run `ghcup` with `-v` to see the exact `gpg` error, which can be used to diagnose why verification is failing. For example, if the key has not been imported, GPG will fail with the following message:
```

2023-08-29 10:15 UTC, hasufell commented
Is this ok? Feel free to extend.

2023-09-01 10:01 UTC, BinderDavid approved these changes
This looks good, thanks!

2023-09-01 10:02 UTC, merged