Document GHC-88747 "Precedence parsing error"
haskellfoundation/error-message-index pull request #486
Opened 2024-05-31 19:08 UTC by Bodigrim

This could be extended further, but at least better than nothing.

2024-05-31 22:58 UTC, BinderDavid commented on message-index/messages/GHC-88747/unary-minus/index.md
> +If one of the clashing operators is unary minus, consider replacing it with `negate`: `5 * negate 3`. Another opportunity is to enable [`{-# LANGUAGE LexicalNegation #-}`](https://ghc.gitlab.haskell.
```suggestion
If one of the clashing operators is unary minus, consider replacing it with `negate`: `5 * negate 3`. Another possibility is to enable [`{-# LANGUAGE LexicalNegation #-}`](https://ghc.gitlab.haskell.org/ghc/doc/users_guide/exts/lexical_negation.html) or [`{-# LANGUAGE NegativeLiterals #-}`](https://ghc.gitlab.haskell.org/ghc/doc/users_guide/exts/negative_literals.html), which makes `-` bind to `3` as early as possible, eliminating the ambiguity.
```
Just small nitpicks :)

2024-05-31 23:01 UTC, BinderDavid requested changes
Thanks. Looks very good! I just have two small suggestions to the wording.

2024-06-01 07:22 UTC, Bodigrim commented
@BinderDavid thanks, updated.

2024-06-01 07:48 UTC, BinderDavid approved these changes

2024-06-01 07:49 UTC, merged