Add example from LYAH to GHC-39999
haskellfoundation/error-message-index pull request #487
Opened 2024-05-31 19:09 UTC by Bodigrim

2024-05-31 22:47 UTC, BinderDavid commented on message-index/messages/GHC-39999/adding-number-to-string/index.md
> +Given that Haskell is a strong statically typed language, it is not a surprise that adding numbers to strings gives a compile-time error. However, one could expect GHC to be unhappy about `"4"`, not
```suggestion
Given that Haskell is a strong statically typed language, it is not a surprise that adding numbers to strings gives a compile-time error. However, one could expect GHC to be unhappy about `"4"`, not about `5` as above! Let's take a deeper look on how the type checker works.
```

2024-05-31 22:50 UTC, BinderDavid commented on message-index/messages/GHC-39999/adding-number-to-string/index.md
> +The compiler first encounters the operator `(+)` which has type `Num a => a -> a -> a`. Thus it infers that both arguments of `(+)` should be of the same type `a`. Looking at the first argument `5` d
```suggestion
The compiler first encounters the operator `(+)` which has type `Num a => a -> a -> a`. Thus it infers that both arguments of `(+)` should be of the same type `a`. Looking at the first argument `5` does not reveal us what `a` is: it could be `Int`, could be `Double`, etc. But the second argument `4` is certainly `String`, so the compiler concludes that `a` should be `String`.
```
The reader of that explanation might not yet have seen type equality constraints, so it might be better to write it out.

2024-05-31 22:52 UTC, BinderDavid requested changes
Thanks a lot for the additional example! I have two small nitpicks, if you agree with them we can merge afterwards :)

2024-06-01 07:22 UTC, Bodigrim commented
@BinderDavid thanks, updated.

2024-06-01 07:51 UTC, BinderDavid approved these changes

2024-06-01 07:52 UTC, merged